require "cliffcantcode.impatient"
require "cliffcantcode.options"
require "cliffcantcode.keymaps"
require "cliffcantcode.plugins"
require "cliffcantcode.colorscheme"
require "cliffcantcode.project"
require "cliffcantcode.bufferline"
require "cliffcantcode.alpha"
require "cliffcantcode.illuminate"
require "cliffcantcode.autocommands"
-- autopairs requires cmp
require "cliffcantcode.cmp"
require "cliffcantcode.autopairs"
require "cliffcantcode.telescope"
require "cliffcantcode.treesitter"
require "cliffcantcode.lualine"
require "cliffcantcode.lsp"
